AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 300
    Runtime: python3.8
    Handler: app.lambda_handler
    Environment:
      Variables:
        HOLIDAY_TABLE: !Ref HolidayTable
        COVER_TABLE: !Ref CoverTable
        REPORTS_BUCKET: !Ref ReportsBucket

Resources:
  loadconfiguration:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/load_configuration/build
      FunctionName: load-configuration
      Events:
        register:
          Type: Api
          Properties:
            Path: /register
            Method: post
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${HolidayTable}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CoverTable}"

  HolidayTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: EmpName
        Type: String

  CoverTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: CoverName
        Type: String

  ReportsBucket:
    Type: AWS::S3::Bucket

  fetchconfiguration:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/fetch_configuration/build
      FunctionName: fetch-configuration
      Runtime: python3.8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${HolidayTable}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CoverTable}"
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:PutObject
            Resource:
              - !GetAtt ReportsBucket.Arn
              - !Sub "${ReportsBucket.Arn}/*"
      Events:
        scheduled:
          Type: Schedule
          Properties:
            Schedule: "rate(1 day)"

Outputs:
  RegisterApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/"
  RegisterFunction:
    Value: !GetAtt loadconfiguration.Arn
  fetchconfiguration:
    Value: !GetAtt fetchconfiguration.Arn
  HolidayTable:
    Value: !Ref HolidayTable
  CoverTable:
    Value: !Ref CoverTable
  ReportsBucket:
    Value: !Ref ReportsBucket
